_target_: walkjump.model.NoiseEnergyModel  # EBM model
arch:
  # Architecture-specific configurations (matching the model)
  n_tokens: 21
  chain_len: 297  # combined hc & lc
  kernel_sizes: [15, 5, 3]
  hidden: 32
  friction: 1.0
  activation: 'relu'
  reg_l2_norm: 0.0
  energy_loss: 'l2'  # Example: L2 norm loss for energy function